[tool.poetry]
name = "notquiteparadise"
version = "0.1.0"
description = ""
authors = ["Snayff"]

[tool.poetry.dependencies]
python = "^3.8"
snecs = "^1.2.1"
pygame = "2.0.0dev6"
pygame-gui = "^0.5.6"
pytweening = "^1.0.3"
tcod = "^11.13.1"
scipy = "^1.4.1"

[tool.poetry.dev-dependencies]
sphinx = "^3.0.4"
mypy = "^0.780"
vulture = "^1.5"
isort = "^4.3.21"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
